version: '3'

services: 

  broker-services:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8008:80"
    deploy:
      mode: replicated
      replicas: 1